import { Footer } from '~/components/footer';
import { Button } from '~/components/button';
import { List, ListItem } from '~/components/list';
import {
  ProjectContainer,
  ProjectHeader,
  ProjectSection,
  ProjectSectionContent,
  ProjectSectionHeading,
  ProjectSectionText,
  ProjectTextRow,
} from '~/layouts/project';
import { baseMeta } from '~/utils/meta';
import styles from './cpms.module.css';

export const meta = () => {
  return baseMeta({
    title: 'CPMS',
    description:
      'CPMS is a contract and project management suite built for data centres, pharma, giga-factories, and infrastructure.',
  });
};

export const Cpms = () => {
  return (
    <>
      <ProjectContainer className={styles.cpms}>
        <ProjectHeader
          title="CPMS – Contract & Project Management Suite"
          description="Built for data centres, pharma, giga-factories, and infrastructure"
        />

        <ProjectSection>
          <ProjectSectionContent>
            <ProjectTextRow>
              <ProjectSectionHeading>Core capabilities</ProjectSectionHeading>
              <ProjectSectionText as="div">
                <List>
                  <ListItem>
                    Multi-contract support including NEC, FIDIC, JCT and bespoke frameworks.
                  </ListItem>
                  <ListItem>
                    Centralised contract register with baselines, options, and key dates.
                  </ListItem>
                  <ListItem>
                    Change management and early warning workflows with clear audit trails.
                  </ListItem>
                  <ListItem>
                    Payment applications, valuations, and approvals backed by source documentation.
                  </ListItem>
                  <ListItem>
                    Integrated EDMS for contract documents, drawings, and correspondence.
                  </ListItem>
                </List>
              </ProjectSectionText>
            </ProjectTextRow>
          </ProjectSectionContent>
        </ProjectSection>

        <ProjectSection>
          <ProjectSectionContent>
            <ProjectTextRow>
              <ProjectSectionHeading>Data, outputs, and integration</ProjectSectionHeading>
              <ProjectSectionText as="div">
                <p className={styles.paragraph}>
                  Export of registers and key reports to PDF, Word, and Excel for board packs and client reporting.
                </p>
                <p className={styles.paragraph}>
                  Import of contract baselines and schedules of amendments provided by clients.
                </p>
                <p className={styles.paragraph}>
                  Planned integration with common scheduling, finance, and procurement tools.
                </p>
              </ProjectSectionText>
            </ProjectTextRow>
          </ProjectSectionContent>
        </ProjectSection>

        <ProjectSection>
          <ProjectSectionContent>
            <ProjectTextRow>
              <ProjectSectionHeading>AI and automation roadmap</ProjectSectionHeading>
              <ProjectSectionText as="div">
                <List>
                  <ListItem>Clause-aware AI assistants to guide users through NEC/FIDIC/JCT processes.</ListItem>
                  <ListItem>Automatic tagging and linking of contract correspondence to relevant clauses.</ListItem>
                  <ListItem>Summaries of change events, risks, and valuation history generated by bots.</ListItem>
                  <ListItem>In-app chat to allow teams to discuss events within context of the live record.</ListItem>
                </List>
              </ProjectSectionText>
            </ProjectTextRow>
          </ProjectSectionContent>
        </ProjectSection>

        <ProjectSection>
          <ProjectSectionContent>
            <ProjectTextRow>
              <ProjectSectionHeading>Deployment and pilots</ProjectSectionHeading>
              <ProjectSectionText as="div">
                <p className={styles.paragraph}>
                  CPMS is in early pilot with partners and built on a cloud-native architecture designed for
                  secure, auditable collaboration across suppliers and client teams.
                </p>
              </ProjectSectionText>
            </ProjectTextRow>
          </ProjectSectionContent>
        </ProjectSection>

        <ProjectSection>
          <ProjectSectionContent>
            <ProjectTextRow>
              <ProjectSectionHeading>Talk to us</ProjectSectionHeading>
              <ProjectSectionText as="div">
                <p className={styles.paragraph}>
                  If you’re interested in piloting CPMS on a live programme or want to understand how it could fit
                  into your existing toolchain, email{' '}
                  <a href="mailto:info@quoralinex.com">info@quoralinex.com</a> or reach out through the contact page.
                </p>
                <Button iconHoverShift href="/contact" iconEnd="arrow-right">
                  Contact us
                </Button>
              </ProjectSectionText>
            </ProjectTextRow>
          </ProjectSectionContent>
        </ProjectSection>
      </ProjectContainer>
      <Footer />
    </>
  );
};
